import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) {
  test(`confirms exclusive role changes and removal at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/administracion/usuarios')
    await expect(page.getByRole('columnheader', { name: 'Acciones' })).toHaveCount(0)
    const row = page.getByRole('row', { name: /ana@example.com/ })
    const visitor = row.getByRole('checkbox', { name: /^Visitante:/ })
    const admin = row.getByRole('checkbox', { name: /^Administrador:/ })
    await visitor.focus()
    await page.keyboard.press('Space')
    const dialog = page.getByRole('dialog', { name: 'Confirmar cambio de rol' })
    await expect(dialog.getByText('Puede visitar la página y descargar contenido.')).toBeVisible()
    await expect(dialog.getByRole('button', { name: 'No, cancelar' })).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(dialog.getByRole('button', { name: 'Sí, cambiar rol' })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.getByRole('button', { name: 'No, cancelar' })).toBeFocused()
    const accessibility = await new AxeBuilder({ page })
      .include('dialog')
      .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
      .analyze()
    expect(accessibility.violations).toEqual([])
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(visitor).toBeFocused()
    await expect(visitor).not.toBeChecked()
    await expect(admin).toBeChecked()
    await visitor.click()
    await dialog.getByRole('button', { name: 'No, cancelar' }).click()
    await expect(admin).toBeChecked()
    await visitor.click()
    await dialog.getByRole('button', { name: 'Sí, cambiar rol' }).click()
    await expect(dialog.getByRole('button', { name: 'Guardando…' })).toBeDisabled()
    await expect(dialog.getByRole('button', { name: 'No, cancelar' })).toBeDisabled()
    await expect(dialog).toHaveCount(0)
    await expect(row.getByRole('status')).toHaveText('Rol actualizado para Ana Ejemplo: Visitante.')
    await expect(visitor).toBeChecked()
    await expect(admin).not.toBeChecked()
    await expect(row.getByRole('checkbox', { name: /^Asistente:/ })).not.toBeChecked()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await visitor.click()
    const removal = page.getByRole('dialog', { name: 'Confirmar retiro de rol' })
    await expect(removal.getByText('El usuario quedará sin un rol asignado.')).toBeVisible()
    await removal.getByRole('button', { name: 'Sí, retirar rol' }).click()
    await expect(removal).toHaveCount(0)
    await expect(visitor).not.toBeChecked()
    await expect(row.getByRole('status')).toHaveText('Rol retirado de Ana Ejemplo.')
    await page.reload()
    await expect(admin).toBeChecked()
  })
}
